<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <RootNamespace>JellyfinTorrentSearch</RootNamespace>
    <AssemblyName>JellyfinTorrentSearch</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jellyfin.Controller" Version="10.10.6" PrivateAssets="All" />
    <PackageReference Include="Jellyfin.Model" Version="10.10.6" PrivateAssets="All" />
    <PackageReference Include="HtmlAgilityPack" Version="1.11.72" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Web\configPage.html" />
    <EmbeddedResource Include="Web\torrentSearch.js" />
  </ItemGroup>

</Project>
